#!/bin/bash

scriptName="$(basename ${BASH_SOURCE[0]})"

print_help() {
    echo "Usage: $scriptName -i path_to_apptainer_def_file [options [arguments]]"
    echo "-h                              : print this help and exit"
    echo "-i path_to_apptainer_def_file   : path to the definition to build"
    echo "-t temporary_directory          : path to use as a temporary directory to build the image in"
    echo "-o output_file_name             : name of the output image"
}

# Default arguments
definitionFile=""
tmpDir=".apptainer_tmpdir"
outputFile=""

while getopts "hi:t:o:" arg; do
  case "$arg" in
    h)  # Print help and exit
        print_help
        exit 0
        ;;
    i)  # Set definition file
        definitionFile="$OPTARG"
        ;;
    t)  # Set temporary directory
        tmpDir="$OPTARG"
        ;;
    o)  # Set the output image name
        outputFile="$OPTARG"
        ;;
    \?) # Unrecognized argument
        echo "Error: unrecognized argument: $arg"
        exit 1
  esac
done

if ! [ -f "$definitionFile" ]; then
  echo "Error: definition file not found: '$definitionFile'"
  exit 1
fi

# Generate output file name if it wasn't given
if [ "$outputFile" = "" ]; then
  definitionDir="$( cd -- "$( dirname -- "${definitionFile}" )" &> /dev/null && pwd )"
  definitionName=$(basename -- "$definitionFile")
  definitionName="${definitionName%.*}"
  outputFile="${definitionDir}/${definitionName}.sif"
fi

tmpDir=$(realpath "$tmpDir")
if [ -d "$tmpDir" ]; then
  echo "Temporary directory already exists: '$tmpDir'"
  exit 1
fi

if ! mkdir -p "$tmpDir"; then
  echo "Failed to create temporary directory: '$tmpDir'"
  exit 1
fi

trap "rm -rf $tmpDir" 0 2 3 15

export APPTAINER_TMPDIR="$tmpDir"

if ! apptainer build "$outputFile" "$definitionFile"; then
  echo "Error: image build failed with exit code $?"
  exit 1
fi

exit 0

