#!/bin/python

# run_debug SCRIPT_PATH [ARGUMENTS...]
#
# This script creates a VSCode debug configuration file and runs a debug session
# for the specified script or executable. Additional arguments are forwarded to the
# script/executable. Linux only for now, and the "xdotool" package must be installed.
#
# Notes:
# The implementation is quite nasty but works if you keep a couple of things in mind:
#   - The script/executable must be within the source repository, or the KRATOS_SOURCE_DIR
#     environment variable must be set to the root of the Kratos repo.
#   - Exactly one instance of VSCode must be open.
#   - The <source_dir>/.vscode/launch.json configuration file gets overwritten.
#
# Details:
#   - This script is primarily meant for running python scripts, or perhaps executables.
#     Other script types might work but they haven't been tested. If the current user
#     has executable rights to the file, it will be considered an executable and called
#     directly. If the file has a python script extension ".py", it is classified as a
#     python script. Otherwise, if the first line of the file is a shebang
#     (begins with "#!"), the file is considered a script that can be interpereted using
#     the executable the shebang points to (python, bash, etc.).
#   - VSCode seems to be broken down into several processes, and I can't tell which is
#     responsible for what. This script just grabs the first process that gets listed
#     for the search term "code". Consequently, you really should have one VSCode instance
#     open, otherwise the debug session might be launched in another one.
#   - A Ctrl + Shift + F5 keystroke is sent to the grabbed process, so your VSCode debug
#     session start must be bound to it (default).

# --- STL Imports ---
import pathlib
import sys
import os
import subprocess


def ParseArguments(args: "list[str]") -> "tuple[str, pathlib.Path, list[str]]":
    """
    Parse the passed list of arguments.

    The first argument must be a path to an executable or a script,
    the rest of the arguments are not checked and will be passed
    to the executable/script when calling them.

    Return:
        - the command that launches the executable/script
        - the path to the executable/script
        - rest of the arguments in a list
    """
    # The first argument is required and must be a path to a python script or an executable
    args = args.copy()
    if not args:
        raise ValueError("Missing positional argument: 'file_path'")

    file_path = pathlib.Path(args.pop(0))
    if file_path.is_file():
        file_path = file_path.resolve().absolute()

        # It's a file, but is it an executable or a script?
        if os.access(str(file_path), os.X_OK): # an executable
            run_command = str(file_path)
            file_path = pathlib.Path()
            debug_type = "cppdbg"
        else: # not an executable
            if file_path.suffix == ".py": # python script
                run_command = str(file_path)
                debug_type = "python"
            else:  # doesn't have the standard python script extension
                with open(file_path, "r") as file:
                    first_line = file.readline()
                    if first_line.startswith("#!"): # has a magic shell command
                        run_command = first_line[2:]
                        args = [str(file_path)] + args
                        debug_type = pathlib.Path(first_line[2:]).stem
                    else: # no idea what it is
                        raise ValueError("'{}' is neither a script nor an executable, or the user has no access to it".format(file_path))
    else: # It's not a file => definitely an error
        message = "'{}' ".format(file_path)
        if file_path.is_dir():
            raise ValueError(message + "is a directory")
        else:
            raise ValueError(message + "does not exist")

    return run_command, debug_type, file_path, args


def GetLauncherTemplate() -> dict:
    """Returns a dictionary that should be filled and then written to the .vscode/launcher.json of the project."""
    return dict((
        ("version", "0.2.0"),
        ("configurations", [
                dict((
                ("name", "generated-debug"),
                ("console", "internalConsole"),
                ("internalConsoleOptions", "neverOpen"),
                ("type", ""),
                ("request", "launch"),
                ("program", ""),
                ("args", []),
                ("stopAtEntry", False),
                ("justMyCode", False),
                ("cwd", os.getcwd()),
                ("environment", [
                    dict((
                        ("name", "OMP_NUM_THREADS"),
                        ("value", "1")
                    ))
                ]),
                ("externalConsole", False),
                ("MIMode", "gdb"),
                ("setupCommands", [dict((
                    ("description", "Enable pretty-printing in gdb"),
                    ("text", "-enable-pretty-printing"),
                    ("ignoreFailures", True)
                ))])
            ))]
        )
    ))


if __name__ == "__main__":
    settings = GetLauncherTemplate()
    launcher, debug_type, file_path, arguments = ParseArguments(sys.argv[1:])

    for configuration in settings["configurations"]:
        configuration["program"] = launcher
        configuration["type"] = debug_type
        configuration["args"] = arguments

    # Get kratos source directory
    if "KRATOS_SOURCE_DIR" in os.environ:
        kratos_source_directory = os.environ["KRATOS_SOURCE_DIR"]
    else:
        directory = file_path.parent
        kratos_source_directory = pathlib.Path(subprocess.check_output("cd {} && git rev-parse --show-toplevel".format(directory), shell = True).decode("utf-8").strip())

    # Write the launcher to ${kratos_source_dir}/.vscode.launch.json
    target_directory = pathlib.Path(kratos_source_directory) / ".vscode"
    target_directory.mkdir(exist_ok = True, parents = True)

    with open(target_directory / "launch.json", "w") as file:
        import json
        json.dump(settings, file, indent = "    ")

    # Get the PID of VSCode
    PIDs = [pid.strip() for pid in subprocess.check_output(["xdotool", "search", "-class", "code"]).decode("utf-8").split("\n") if pid.strip()]
    PID = PIDs[0]

    active_window = subprocess.check_output(["xdotool", "getactivewindow"]).decode("utf-8").strip()

    # Send the debug keystroke to VSCode
    subprocess.run("xdotool windowactivate {} && xdotool key Ctrl + Shift + F5 && xdotool windowactivate {}".format(PID, active_window), shell = True)
